travis:
  secure:
    BINSTAR_TOKEN: S4e15f1MEMsN+yomscWpMZCCIDMcw0mEncbsd/dIIWZeg+Wwj/tgp6vog3m3Rhx3USD03Vh4WHukJXtwmd1uuy6FIuq6ZyVHP0dj6x0M8w+5MMDQFL/n1Zmy4D0R9kZL+h6fN+0b8KdexQW7uAp7lQAt6Gjf3d+WFSsfiuDEn0Koi+P4O/obtvy+xeXbtuf9Wwz6mUDbSc5Oxa3inTqgv4+Mdq9pwRLy1XQng8XO4H+YS37zXV0pCs0ZaTuQjQmyanyg2mclUWAaOLgk6vSezNfDfLsfGV2Oa69QX5OyuMRSuvs1cIbXaAEO42QXimlmEy3pS+HDMIOKY08guxNmfBI47IcMJMme3z8LD0jNR2dzzYmgltI7lmCqLujAfIOeUDRbCtIr84i6yAksGAgxYg+t9WzJU5APt+82I+NQkZbK4CNUOYi7NP867Ykut7AugE+tctdNOjAEDpAmPW2mD4DYwrY8FwUbiaYUw6GUXGCLKMCKzcSCw9jkPnVsS5KemffIBNeoBCy9iZFRE4d+1VhojYAg5m8ivPMQsKhtqxXfIHYTOVRUxCxfxwMBkNzY2EAMWOP63o3N3LVjRKejJrLesI1IiSrEmify+jlBYOgKFcTB9uFx361H2/o9WtXnxhtxYVeHNGCBsJ0LyhJTjDsrfSHZaVXoJy441Z8VRC8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
