travis:
  secure:
    BINSTAR_TOKEN: lTe+PRXfEtQCyt7YfBk1D025SjguuLw9Uu53p8zOAJT2OrrwZnlxwJlRnn03h6oJc6lHE2elOtgmRI0BeaMxmg74mM3rgsTNMicHY1R1AR+E6mf+Qfi9HKksch8dTG5eT4qUF60MY3rDGDLD+2Sx/v+MF+9mB3C6289IHYZcx0PVXRkF0p0j5sf62+irKsfHmh/9RL7wrx2f52OBmH2QZNG7r6XKmzWOFXmDX+UWIBYb7pH+OKPW4l4fdif43urXjh+WXwNkkIOp+8g+bSo0TE5kXM3h5yVSANr9YLgWx26s1uId6tKMi/9r2DRdSAUGQYFGnqu7GzgBFirYKalCqGeRwzKPoQH8PRmHdr8CLLnpMQH4Ev+FeOocNDslYHuNFCRmw7qN812xttlzE0o+igrRQh5o8dusbABnouQ8T8QotcSagE8l+qQ0c5kC7YNpmPCNglqmvSLcCZrFHrqtlN8IQLgiYf2kcbPaCZJQEIf5yEdrWZo3rULdQMjBD0tnqDfpGjaFMfd9o71dm4iDRmvftLNYoMr3AK3YhsBhZgZk9QCULC/yEWvs4Jd/EasVf5OrT9S+ornKGfW7J2QE0bE+8oCL1v0dl7KLtu2Xp1ZmL64CkQmXytlCsrhPcXwBgEv3tWOahMilbvyrJSfUPLv8BZYyrk4hyEI5tATwXzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
